/var/log/motion/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 0640 root root
    sharedscripts
    postrotate
        /usr/bin/systemctl reload motioneye >/dev/null 2>&1 || true
    endscript
} 