[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:motioneye]
command=motioneye
directory=/var/lib/motioneye
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/motioneye.err.log
stdout_logfile=/var/log/motioneye.out.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log 